# Generated by Django 3.2 on 2021-04-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=250)),
                ('house_number', models.CharField(max_length=25)),
                ('administrative_zone', models.CharField(max_length=250)),
                ('postal_zone', models.CharField(max_length=250)),
            ],
        ),
    ]
